version: 2
jobs:
    build:
        docker:
            - image: circleci/node:9.3
        working_directory: ~/circleci-start
        steps:
            - checkout
            - run: npm install
            - run: npm run build
            - run: mkdir -p tmp
            - run: cp -r dist/ tmp/dist/
            - run: cp .circleci/setup-heroku.sh tmp/
            - persist_to_workspace:
                root: tmp
                paths:
                    - setup-heroku.sh
                    - dist
    deploy:
        machine: true
        working_directory: ~/circleci-start
        steps:
            - checkout
            - run: echo "Hello World"
            - attach_workspace:
                at: tmp
            - run: pwd && ls -a
            - run: cd tmp && pwd && ls -a
            - run: cd dist && pwd && ls -a
            # - run: cd dist/dist && pwd && ls -a
            # - run: cat ./dist/index.html

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
