version: 2
jobs:
    build:
        docker:
            - image: circleci/node:9.3
        working_directory: ~/circleci-start
        steps:
            - checkout
            - run: npm install
            - run: npm run build
            - run: mkdir -p tmp
            - run: cp -r dist/ tmp/dist/
            - run: cp .circleci/setup-heroku.sh tmp/
            - persist_to_workspace:
                root: tmp
                paths:
                    - setup-heroku.sh
                    - dist
    deploy:
        machine: true
        working_directory: ~/circleci-start
        environment:
            HEROKU_APP: "nameless-basin-38811"
        steps:
            - checkout
            - attach_workspace:
                at: tmp
            - run:
                name: Run Setup Script
                command: bash tmp/setup-heroku.sh
            - add_ssh_keys:
                fingerprints:
                    - "cc:40:d1:99:63:e0:1f:cb:6f:0c:32:7b:be:22:2c:87"
            - run:
                name: Deploy Master to Heroku
                command: |
                    heroku git:remote -a HEROKU_APP
                    git push --force git@heroku.com:$HEROKU_APP HEAD:refs/heads/master
                    heroku run node index.js


workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
