version: 2
jobs:
    build:
        docker:
            - image: circleci/node:9.3
        working_directory: ~/circleci-start
        steps:
            - checkout
            - run: npm install
            - run: npm run build
            - persist_to_workspace:
                root: ~/circleci-start
                paths: dist
    deploy:
        machine: true
        working_directory: ~/circleci-start
        steps:
            # - attach_workspace:
            #     at: dist
            - run: pwd && ls -a
            - run: cd dist && pwd && ls -a
            # - run: cd dist/dist && pwd && ls -a
            # - run: cat ./dist/index.html

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
