version: 2
jobs:
    build:
        docker:
            - image: circleci/node:9.3
        working_directory: ~/circleci-start
        steps:
            - checkout
            - run: npm install
            - run: npm run build
    deploy:
        machine: true
        working_directory: ~/circleci-start
        steps:
            - checkout
            - run: pwd && ls ./dist
            # - run: cat ./dist/index.html

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
