version: 2
jobs:
    build:
        docker:
            - image: circleci/node:9.3
        steps:
            - checkout
            - run: echo "hello world"
    deploy:
        docker:
            - image: circleci/node:9.3
        steps:
            - checkout
            - run: echo "hello world 2"

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
